export const POPUP_KEYS = {
  LOGIN_POPUP_OPEN: 'LOGIN_POPUP_OPEN',
  SIGNUP_POPUP_OPEN: 'SIGNUP_POPUP_OPEN',
  INTERESTS_POPUP_OPEN: 'INTERESTS_POPUP_OPEN',
  VIEWS_POPUP_OPEN: 'VIEWS_POPUP_OPEN',
};

export const LOCAL_STORAGE_KEYS = {
  LOGGED_IN_USER_EMAIL: 'LOGGED_IN_USER_EMAIL',
};